services:
  - type: web
    name: smart-fitness-backend
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: DATABASE_URL
        value: postgres://postgres:12thNight%2FWYW%21@db.ghyjrdutukfmiqckgdks.supabase.co:6543/postgres