services:
  - type: web
    name: smart-fitness-backend
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.ghyjrdutukfmiqckgdks:12thNight%2FWYW%21@aws-0-ca-central-1.pooler.supabase.com:6543/postgres